# Generated by Django 3.1.5 on 2021-03-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_csv', '0003_auto_20210311_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheme',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semicolon (;)')], default=',', max_length=1),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double-quote (")')], default='"', max_length=1),
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('test', 'TEST')], max_length=10)),
                ('order', models.PositiveIntegerField()),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dummy_csv.scheme')),
            ],
        ),
    ]
