# Generated by Django 3.1.5 on 2021-03-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_csv', '0007_auto_20210311_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='column',
            options={'ordering': ['-order']},
        ),
        migrations.AddField(
            model_name='column',
            name='parameter_one',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='column',
            name='parameter_two',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='column',
            name='type',
            field=models.CharField(choices=[('fullname', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain', 'Domain name'), ('phone', 'Phone number'), ('company', 'Company name'), ('text', 'Text'), ('int', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=10),
        ),
    ]
